// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveMessage(arg1:main.MessageActionInput):Promise<main.Message>;

export function AuthorizeProfile(arg1:main.DeviceAuthInput):Promise<main.Profile>;

export function DeleteMessage(arg1:main.MessageActionInput):Promise<main.Message>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadAttachment(arg1:main.DownloadAttachmentInput):Promise<main.DownloadResult>;

export function GetInitialState():Promise<main.InitialState>;

export function LoadMailbox(arg1:main.MailboxRequest):Promise<main.MailboxPayload>;

export function SaveProfile(arg1:main.ProfileInput):Promise<main.Profile>;

export function SaveProfileToken(arg1:main.TokenInput):Promise<main.Profile>;

export function SelectProfile(arg1:string):Promise<void>;

export function SendMessage(arg1:main.SendMessageInput):Promise<main.SendResult>;

export function TestBaseURL(arg1:string,arg2:string):Promise<main.ConnectionStatus>;

export function UnarchiveMessage(arg1:main.MessageActionInput):Promise<main.Message>;
