// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveMessage(arg1) {
  return window['go']['main']['App']['ArchiveMessage'](arg1);
}

export function AuthorizeProfile(arg1) {
  return window['go']['main']['App']['AuthorizeProfile'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateDomain(arg1) {
  return window['go']['main']['App']['CreateDomain'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadAttachment(arg1) {
  return window['go']['main']['App']['DownloadAttachment'](arg1);
}

export function GetEndpointDiagnostics(arg1) {
  return window['go']['main']['App']['GetEndpointDiagnostics'](arg1);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function ListAuditLogs(arg1) {
  return window['go']['main']['App']['ListAuditLogs'](arg1);
}

export function LoadMailbox(arg1) {
  return window['go']['main']['App']['LoadMailbox'](arg1);
}

export function PreviewAttachment(arg1) {
  return window['go']['main']['App']['PreviewAttachment'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveProfileToken(arg1) {
  return window['go']['main']['App']['SaveProfileToken'](arg1);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetMessageStatus(arg1) {
  return window['go']['main']['App']['SetMessageStatus'](arg1);
}

export function TestBaseURL(arg1, arg2) {
  return window['go']['main']['App']['TestBaseURL'](arg1, arg2);
}

export function UnarchiveMessage(arg1) {
  return window['go']['main']['App']['UnarchiveMessage'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
